### ISSUE TITLE
Glutenallergi

### ISSUE THREAD

**Issue by joelso** [FrostDigital/frost-granola#1]
Är recept kompatibelt för glutenallergiker?

**Comment by joelso** [comment]
@veronicaborjesson Vad tror du?

**Comment by veronicaborjesson** [comment]
@joelso haha låter gott! :honey_pot: det enda är att köra på havregryn som är "rent", dvs inte malt i samma kvarn som vete men annars är det glutenfrigodkänt! :+1:

**Comment by JosefinAndersson** [comment]
Om man använder glutenfria havregryn så ska det fungera för glutenallergiker

**Comment by joelso** [comment]
@veronicaborjesson @JosefinAndersson :+1:

**Comment by joelso** [comment]
Vet ni något specifikt märke som finns på Coop/ICA?

**Comment by veronicaborjesson** [comment]
@joelso semper brukar ha

**Comment by se-rg-os** [comment]
@joelso AXA

**Comment by joelso** [comment]
Ok, jag är nöjd med det - _stänger_
